version: '3'

services:
  elk-service:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ./service:/home/service
      - ./logstash/conf/pipeline.conf:/etc/logstash/conf.d/pipeline.conf
      - ./logstash/tests/logstash-tutorial.log:/home/Downloads/logstash-tutorial.log


